[package]
name = "dp-slot-duration-runtime-api"
authors = { workspace = true }
description = "Runtime API to get slot duration during the transition from 12s to 6s block time"
edition = "2021"
license = "GPL-3.0-only"
version = "0.1.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]
[dependencies]
# Substrate
frame-support = { workspace = true }
parity-scale-codec = { workspace = true }
sp-api = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# Cumulus
cumulus-primitives-core = { workspace = true }

[features]
default = [ "std" ]
std = [
	"cumulus-primitives-core/std",
	"parity-scale-codec/std",
	"sp-api/std",
	"sp-core/std",
	"sp-io/std",
	"sp-std/std",
]
